[package]
name = "axion-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axion-core = { path = "../axion-core" }
axum = "0.7"
tower-http = { version = "0.5", features = ["cors"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
