"use client";

import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface MissionStateSlim {
  data_payload: Record<string, unknown>;
  design_tokens?: { theme_preset?: string; layout_strategy?: string };
  suggested_widgets?: string[];
}

interface ActionBarProps {
  intent: string;
  missionState: MissionStateSlim;
  onNewMission: (intent: string) => void;
  /** Mission ID — used for server-side export and targeted refinement. */
  missionId?: string;
  /** Called when the user submits a refinement prompt. */
  onRefine?: (intent: string) => void;
  /** True while a refinement is actively streaming. */
  isRefining?: boolean;
  /** Error message from last refinement attempt, if any. */
  refineError?: string | null;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function extractSubject(intent: string): string {
  const stopwords = new Set(["a","an","the","and","or","for","in","on","of","to","into","about","with","from","by","is","are","was","were","do","does","did","how","what","why","when","where","who","which","that","this","these","those","will","can","could","should","would","let","make","create","build","plan","find","get","give","show","tell","write","design","analyze","research","synthesize","generate","develop","implement","compare","review","explain"]);
  const words = intent.replace(/['"]/g, "").split(/\s+/);
  const meaningful = words.filter(w => w.length > 2 && !stopwords.has(w.toLowerCase()));
  if (meaningful.length === 0) return intent.slice(0, 32);
  return meaningful.slice(0, 3).join(" ");
}

function generateMarkdown(intent: string, data: Record<string, unknown>): string {
  const lines: string[] = [`# Mission Report: ${intent}`, "", `_Generated by Axion — ${new Date().toLocaleDateString()}_`, ""];
  for (const [key, value] of Object.entries(data)) {
    const title = key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
    lines.push(`## ${title}`, "");
    if (Array.isArray(value)) {
      if (value.length > 0 && typeof value[0] === "object") {
        const headers = Object.keys(value[0] as object);
        lines.push(`| ${headers.join(" | ")} |`);
        lines.push(`| ${headers.map(() => "---").join(" | ")} |`);
        for (const row of value) {
          const r = row as Record<string, unknown>;
          lines.push(`| ${headers.map(h => String(r[h] ?? "")).join(" | ")} |`);
        }
      } else {
        for (const v of value) lines.push(`- ${v}`);
      }
    } else if (typeof value === "object" && value !== null) {
      for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
        lines.push(`**${k.replace(/_/g, " ")}**: ${v}`);
      }
    } else {
      lines.push(String(value));
    }
    lines.push("");
  }
  return lines.join("\n");
}

function downloadMarkdown(intent: string, data: Record<string, unknown>) {
  const md = generateMarkdown(intent, data);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `opalzero-report-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

async function exportViaServer(missionId: string, format: "md" | "csv" | "html") {
  const res = await fetch(`http://localhost:8080/missions/${missionId}/export?format=${format}`);
  if (!res.ok) throw new Error(`Export failed: ${res.status}`);
  const blob = await res.blob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `opalzero-report-${missionId}.${format}`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Glass constants ───────────────────────────────────────────────────────────

const GLASS = {
  background: "linear-gradient(rgba(255,255,255,0.04), rgba(255,255,255,0.016))",
  border: "1px solid rgba(255,255,255,0.08)",
  backdropFilter: "blur(28px) saturate(130%)",
  WebkitBackdropFilter: "blur(28px) saturate(130%)",
  boxShadow: "0 1px 0 0 rgba(255,255,255,0.06) inset, 0 0 0 1px rgba(255,255,255,0.05), 0 40px 80px -30px rgba(0,0,0,0.70)",
} as const;

// ── ActionBar ─────────────────────────────────────────────────────────────────

export function ActionBar({
  intent,
  missionState,
  onNewMission,
  missionId,
  onRefine,
  isRefining = false,
  refineError = null,
}: ActionBarProps) {
  const [refineOpen, setRefineOpen]   = useState(false);
  const [refineText, setRefineText]   = useState("");
  const refineInputRef = useRef<HTMLTextAreaElement>(null);

  // Auto-focus input when the refine panel opens
  useEffect(() => {
    if (refineOpen) setTimeout(() => refineInputRef.current?.focus(), 80);
  }, [refineOpen]);

  // Close refine panel when streaming starts
  useEffect(() => {
    if (isRefining) setRefineOpen(false);
  }, [isRefining]);

  function handleRefineSubmit() {
    const trimmed = refineText.trim();
    if (!trimmed || isRefining) return;
    onRefine?.(trimmed);
    setRefineText("");
  }

  const subject  = extractSubject(intent);
  const strategy = missionState.design_tokens?.layout_strategy ?? "Overview";

  const thirdActionLabel =
    strategy === "FocusOnCharts" ? "Compare More Data" :
    strategy === "Narrative"     ? "Plan Next Steps" :
    strategy === "DataHeavy"     ? "Summarise Key Findings" :
                                   `Deep Dive: ${subject}`;
  const thirdActionIntent =
    strategy === "FocusOnCharts" ? `Compare alternative data sources for: ${subject}` :
    strategy === "Narrative"     ? `Create a detailed action plan based on: ${intent}` :
    strategy === "DataHeavy"     ? `Summarise and simplify the key findings from: ${intent}` :
                                   `Deep dive research into ${subject}`;

  const topActions = [
    {
      icon: "↓",
      label: "Export Report",
      desc: "Download as Markdown",
      accent: "#6ee7b7",
      onClick: () => {
        if (missionId) {
          exportViaServer(missionId, "md").catch(() =>
            downloadMarkdown(intent, missionState.data_payload)
          );
        } else {
          downloadMarkdown(intent, missionState.data_payload);
        }
      },
    },
    {
      icon: "⟳",
      label: isRefining ? "Refining…" : (refineOpen ? "Cancel Refine" : "Refine Mission"),
      desc: isRefining ? "Streaming refinement…" : "Add to this mission inline",
      accent: "var(--opalzero-accent, #a7cadc)",
      onClick: () => {
        if (!isRefining) setRefineOpen(v => !v);
      },
    },
    {
      icon: "→",
      label: thirdActionLabel,
      desc: "Spawn a follow-up mission",
      accent: "#f59e0b",
      onClick: () => onNewMission(thirdActionIntent),
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.25, duration: 0.35 }}
      style={{ marginTop: 32, borderRadius: 18, overflow: "hidden", ...GLASS }}
    >
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div style={{
        padding: "12px 20px",
        borderBottom: "1px solid rgba(255,255,255,0.07)",
        display: "flex",
        alignItems: "center",
        gap: 8,
      }}>
        <span style={{ fontSize: 9, fontWeight: 700, letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(255,255,255,0.28)" }}>
          Next Steps
        </span>
        <span style={{ flex: 1, height: 1, background: "rgba(255,255,255,0.06)" }} />
        {isRefining ? (
          <>
            <span style={{
              width: 8, height: 8, borderRadius: "50%", flexShrink: 0,
              background: "var(--opalzero-accent, #a7cadc)",
              boxShadow: "0 0 8px var(--opalzero-accent, #a7cadc)",
              animation: "neural-pulse 1.4s ease-in-out infinite",
            }} />
            <span style={{ fontSize: 9, color: "rgba(167,202,220,0.75)", fontWeight: 500 }}>
              Refining…
            </span>
          </>
        ) : (
          <>
            <span style={{ width: 6, height: 6, borderRadius: "50%", background: "#34d399", boxShadow: "0 0 8px #34d399" }} />
            <span style={{ fontSize: 9, color: "rgba(52,211,153,0.7)", fontWeight: 500 }}>Mission complete</span>
          </>
        )}
      </div>

      {/* ── Action buttons row ───────────────────────────────────────────── */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 0 }}>
        {topActions.map((a, i) => (
          <motion.button
            key={a.label}
            onClick={a.onClick}
            whileHover={{ background: `${a.accent}12` }}
            transition={{ duration: 0.15 }}
            disabled={isRefining && a.label.startsWith("Refin")}
            style={{
              textAlign: "left",
              padding: "16px 20px",
              borderRight: i < 2 ? "1px solid rgba(255,255,255,0.07)" : "none",
              cursor: isRefining && a.label.startsWith("Refin") ? "default" : "pointer",
              background: refineOpen && a.label.includes("Refine")
                ? "rgba(167,202,220,0.08)"
                : "transparent",
              display: "flex",
              alignItems: "flex-start",
              gap: 12,
              opacity: isRefining && !a.label.startsWith("Refin") ? 0.55 : 1,
              transition: "opacity 0.2s",
            }}
          >
            <span style={{
              width: 32, height: 32, borderRadius: 10, flexShrink: 0,
              display: "flex", alignItems: "center", justifyContent: "center",
              background: `${a.accent}18`,
              border: `1px solid ${a.accent}30`,
              color: a.accent,
              fontSize: 14, fontWeight: 700,
            }}>
              {isRefining && a.label.includes("Refin") ? (
                <span style={{ width: 12, height: 12, borderRadius: "50%", border: `2px solid ${a.accent}`, borderTopColor: "transparent", display: "inline-block", animation: "spin 0.8s linear infinite" }} />
              ) : a.icon}
            </span>
            <div>
              <p style={{ fontSize: 13, fontWeight: 600, color: "rgba(255,255,255,0.85)", marginBottom: 2 }}>
                {a.label}
              </p>
              <p style={{ fontSize: 11, color: "rgba(255,255,255,0.38)" }}>
                {a.desc}
              </p>
            </div>
          </motion.button>
        ))}
      </div>

      {/* ── Inline Refine panel ──────────────────────────────────────────── */}
      <AnimatePresence>
        {refineOpen && !isRefining && (
          <motion.div
            key="refine-panel"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ type: "spring", stiffness: 340, damping: 30 }}
            style={{ overflow: "hidden", borderTop: "1px solid rgba(255,255,255,0.07)" }}
          >
            <div style={{ padding: "16px 20px 18px" }}>
              {/* Sub-header */}
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}>
                <span style={{ width: 20, height: 20, borderRadius: 6, background: "rgba(167,202,220,0.15)", border: "1px solid rgba(167,202,220,0.28)", display: "flex", alignItems: "center", justifyContent: "center", color: "#a7cadc", fontSize: 11 }}>⟳</span>
                <p style={{ fontSize: 11, fontWeight: 700, color: "rgba(255,255,255,0.70)", letterSpacing: "0.04em" }}>
                  Refine this mission
                </p>
                <p style={{ fontSize: 11, color: "rgba(255,255,255,0.28)" }}>
                  — new cards merge into the existing bento grid
                </p>
              </div>

              {/* Input area */}
              <div style={{
                display: "flex",
                gap: 10,
                padding: "10px 14px",
                borderRadius: 14,
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.10)",
              }}>
                <textarea
                  ref={refineInputRef}
                  rows={1}
                  value={refineText}
                  onChange={(e) => {
                    setRefineText(e.target.value);
                    const el = e.target;
                    el.style.height = "auto";
                    el.style.height = `${Math.min(el.scrollHeight, 120)}px`;
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      handleRefineSubmit();
                    }
                    if (e.key === "Escape") setRefineOpen(false);
                  }}
                  placeholder={`What else do you want to know about "${extractSubject(intent)}"?`}
                  style={{
                    flex: 1,
                    background: "transparent",
                    color: "rgba(255,255,255,0.88)",
                    fontSize: 13,
                    lineHeight: "1.55",
                    outline: "none",
                    resize: "none",
                    minHeight: 24,
                    maxHeight: 120,
                    overflow: "hidden",
                    fontFamily: "var(--opalzero-font-main)",
                  }}
                  className="placeholder-gray-500"
                />
                <button
                  onClick={handleRefineSubmit}
                  disabled={!refineText.trim()}
                  style={{
                    alignSelf: "flex-end",
                    padding: "6px 16px",
                    borderRadius: 9,
                    background: refineText.trim() ? "var(--opalzero-accent, #a7cadc)" : "rgba(255,255,255,0.08)",
                    color: refineText.trim() ? "var(--opalzero-accent-fg, #07090c)" : "rgba(255,255,255,0.28)",
                    fontSize: 12,
                    fontWeight: 700,
                    cursor: refineText.trim() ? "pointer" : "default",
                    transition: "background 0.15s, color 0.15s",
                    letterSpacing: "0.02em",
                  }}
                >
                  Refine →
                </button>
              </div>

              {/* Inline error */}
              {refineError && (
                <p style={{ marginTop: 8, fontSize: 11, color: "#f87171" }}>
                  ⚠ {refineError}
                </p>
              )}

              {/* Suggested refinements */}
              <div style={{ marginTop: 10, display: "flex", flexWrap: "wrap", gap: 6 }}>
                {[
                  "Compare alternatives side-by-side",
                  "Add cost breakdown",
                  "Include recent news",
                  "Summarise key risks",
                ].map((s) => (
                  <button
                    key={s}
                    onClick={() => setRefineText(s)}
                    style={{
                      fontSize: 11,
                      padding: "4px 10px",
                      borderRadius: 999,
                      background: "rgba(167,202,220,0.08)",
                      border: "0.5px solid rgba(167,202,220,0.22)",
                      color: "rgba(167,202,220,0.70)",
                      cursor: "pointer",
                      transition: "background 0.12s",
                    }}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Inline refining status bar */}
      <AnimatePresence>
        {isRefining && (
          <motion.div
            key="refining-bar"
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            style={{
              borderTop: "1px solid rgba(167,202,220,0.15)",
              padding: "10px 20px",
              display: "flex",
              alignItems: "center",
              gap: 10,
              background: "rgba(167,202,220,0.04)",
            }}
          >
            <span style={{ width: 8, height: 8, borderRadius: "50%", background: "var(--opalzero-accent,#a7cadc)", animation: "neural-pulse 1.4s ease-in-out infinite", flexShrink: 0 }} />
            <p style={{ fontSize: 11, color: "rgba(255,255,255,0.50)" }}>
              Refinement in progress — new cards will appear in the bento grid above…
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
