use serde::{Deserialize, Serialize};
use uuid::Uuid;
use std::collections::HashMap;

// ── Human-in-the-loop signalling ──────────────────────────────────────────────

/// Magic prefix written to a task's `result` field by the `feedback` tool.
/// `validate_mission` scans for this prefix to detect a requested human pause.
pub const AWAITING_FEEDBACK_PREFIX: &str = "__AWAITING_FEEDBACK__: ";

/// Returned by `run_mission` when the mission is paused awaiting human input.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandshakeRequest {
    /// ID of the persisted snapshot (`missions/<id>.json`).
    pub mission_id: String,
    /// The question the agent wants the user to answer.
    pub question: String,
}

// ── Design Tokens ─────────────────────────────────────────────────────────────

/// Visual theme tokens emitted by the Analyst alongside mission data.
///
/// The frontend consumes these to apply a liquid-glassmorphism theme whose
/// intensity and colour palette match the nature of the mission.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DesignTokens {
    /// Primary accent hex colour — glows and active-element highlights.
    /// Should be low-saturation, high-luminosity (Apple-inspired).
    #[serde(default = "default_primary_accent")]
    pub primary_accent: String,
    /// Glassmorphism intensity, clamped to [0.0, 1.0].
    /// 0.0 = solid cards, 1.0 = maximum frosted-glass blur.
    #[serde(default = "default_glass_intensity")]
    pub glass_intensity: f32,
    /// Narrative theme: `"fintech"` | `"organic"` | `"research"` | `"minimalist"` | `"creative"`.
    #[serde(default = "default_theme_preset")]
    pub theme_preset: String,
    /// Card spacing: `"spacious"` or `"compact"`.
    #[serde(default = "default_layout_density")]
    pub layout_density: String,
    /// Card corner radius in pixels (default 24 for organic softness).
    #[serde(default = "default_border_radius")]
    pub border_radius: u32,
    /// Card surface background opacity (0.0–1.0, default 0.06 for frosted look).
    #[serde(default = "default_surface_opacity")]
    pub surface_opacity: f32,
    /// Frontend layout hint: `"Overview"` | `"FocusOnCharts"` | `"DataHeavy"` | `"Narrative"`.
    #[serde(default = "default_layout_strategy")]
    pub layout_strategy: String,
}

fn default_primary_accent()   -> String { "#8b9cf4".to_string() } // soft indigo
fn default_glass_intensity()  -> f32    { 0.60 }
fn default_theme_preset()     -> String { "minimalist".to_string() }
fn default_layout_density()   -> String { "spacious".to_string() }
fn default_border_radius()    -> u32    { 24 }
fn default_surface_opacity()  -> f32    { 0.06 }
fn default_layout_strategy()  -> String { "Overview".to_string() }

impl Default for DesignTokens {
    fn default() -> Self {
        DesignTokens {
            primary_accent:   default_primary_accent(),
            glass_intensity:  default_glass_intensity(),
            theme_preset:     default_theme_preset(),
            layout_density:   default_layout_density(),
            border_radius:    default_border_radius(),
            surface_opacity:  default_surface_opacity(),
            layout_strategy:  default_layout_strategy(),
        }
    }
}

// ── Mission State ─────────────────────────────────────────────────────────────

/// The canonical final output of an Axion mission, produced by `finalize_mission_state`.
///
/// This is a raw, client-agnostic fact payload.  The web frontend transforms it
/// into UI components via its `ApplicationMapper`; other clients (CLI, API) can
/// consume `data_payload` directly without any rendering logic.
#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct MissionState {
    /// Whether the mission fully resolved the original intent.
    pub intent_resolved: bool,
    /// Free-form JSON object whose keys and value types are determined by the
    /// Analyst agent.  Keys should be descriptive (e.g. `cheapest_flight`,
    /// `hotel_options`, `total_cost`) and values can be scalars, arrays, or
    /// nested objects.
    pub data_payload: serde_json::Value,
    /// Human-readable notes the agent logged during synthesis (quality checks,
    /// data sources, caveats).
    #[serde(default)]
    pub verification_logs: Vec<String>,
    /// Visual theme tokens generated by the Analyst to match the mission's
    /// character.  Falls back to the minimalist indigo theme when absent.
    #[serde(default)]
    pub design_tokens: DesignTokens,
    /// Optional hints for the frontend to render specific component types for
    /// named payload keys, e.g. `["ChartCard:price_history", "ImageCard:product_visual"]`.
    #[serde(default)]
    pub suggested_widgets: Vec<String>,
}

// ── Agent roles ───────────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub enum AgentRole {
    WebSearcher,
    Analyst,
    Planner,
    /// Executes Python code for complex math, data transformation, or analysis.
    Coder,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Task {
    pub id: Uuid,
    /// Full natural-language task description.
    pub intent: String,
    /// Short, sanitized key used as the ContextBus entry for this task's result.
    /// Derived from the first few significant words of `intent`, so it is both
    /// human-readable and location-aware (e.g. `find_hotels_in_seoul` vs
    /// `find_hotels_in_rome`).
    pub slug: String,
    pub status: TaskStatus,
    pub role: AgentRole,
    pub result: Option<String>,
    /// Slugs of tasks that must reach `Completed` before this task is eligible
    /// to run.  An empty vec means "no prerequisites — run immediately".
    /// Using `#[serde(default)]` keeps older mission snapshots (which either
    /// omit the field or carry UUID strings from the previous schema) safe to
    /// deserialise — unknown strings simply won't match any slug and are ignored.
    #[serde(default)]
    pub depends_on: Vec<String>,
    /// Tool names that must not be offered to the agent for this task.
    /// Used by the re-planner to steer repair tasks away from previously
    /// failing tools (e.g. `python_interpreter` after a Coder failure).
    #[serde(default)]
    pub excluded_tools: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum TaskStatus {
    Pending,
    Running,
    Completed,
    Failed,
}

impl AgentRole {
    #[allow(dead_code)]
    pub fn as_str(&self) -> &'static str {
        match self {
            AgentRole::WebSearcher => "WebSearcher",
            AgentRole::Analyst => "Analyst",
            AgentRole::Planner => "Planner",
            AgentRole::Coder => "Coder",
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct ContextBus {
    pub data: HashMap<String, String>,
}

impl ContextBus {
    /// Wipe all stored results. Call this before re-running a mission to
    /// guarantee no stale data from a previous execution leaks through.
    pub fn clear(&mut self) {
        self.data.clear();
    }
}
/// A directory the Wasm executor should expose to the guest module.
///
/// `host` is a path on the Axion host (relative to CWD at runtime).
/// `guest` is the absolute path the Wasm code will see (e.g. `"/missions"`).
/// `readonly` restricts the preopen to read-only `DirPerms::READ | FilePerms::READ`.
#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct WasmPreopen {
    pub host: String,
    pub guest: String,
    #[serde(default = "bool_true")]
    pub readonly: bool,
}

fn bool_true() -> bool {
    true
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Tool {
    pub name: String,
    pub description: String,
    pub parameters: ToolParameters,
    /// Whether the tool dispatch is async (e.g. `web_search`).
    /// Loaded from manifests; skipped when serialising for the OpenAI API.
    #[serde(default, skip_serializing)]
    pub is_async: bool,
    /// Host directories to expose to the Wasm module via WASI preopens.
    /// Loaded from manifests; skipped when serialising for the OpenAI API.
    #[serde(default, skip_serializing)]
    pub preopens: Vec<WasmPreopen>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ToolParameters {
    #[serde(rename = "type")]
    pub param_type: String,
    pub properties: HashMap<String, ParameterProperty>,
    pub required: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ParameterProperty {
    #[serde(rename = "type")]
    pub prop_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub items: Option<Box<ParameterProperty>>,
}

impl Tool {
    pub fn calculator() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "operation".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some("The operation to perform: 'add', 'subtract', 'multiply', or 'divide'".to_string()),
                items: None,
            },
        );
        properties.insert(
            "values".to_string(),
            ParameterProperty {
                prop_type: "array".to_string(),
                description: Some("Array of numbers to perform the operation on".to_string()),
                items: Some(Box::new(ParameterProperty {
                    prop_type: "number".to_string(),
                    description: None,
                    items: None,
                })),
            },
        );

        Tool {
            name: "calculator".to_string(),
            description: "Performs mathematical calculations (add, subtract, multiply, divide)".to_string(),
            is_async: false,
            preopens: vec![],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["operation".to_string(), "values".to_string()],
            },
        }
    }

    pub fn write_file() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "filename".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some("Name of the file to write (e.g. 'trip_report.md'). Must not contain path separators.".to_string()),
                items: None,
            },
        );
        properties.insert(
            "content".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some("The full text content to write into the file.".to_string()),
                items: None,
            },
        );

        Tool {
            name: "write_file".to_string(),
            description: "Writes text content to a file inside the output/ directory. Use this to persist reports or summaries to disk.".to_string(),
            is_async: false,
            preopens: vec![],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["filename".to_string(), "content".to_string()],
            },
        }
    }

    pub fn web_search() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "query".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some("The search query to execute".to_string()),
                items: None,
            },
        );

        Tool {
            name: "web_search".to_string(),
            description: "Searches the web for information".to_string(),
            is_async: true,
            preopens: vec![],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["query".to_string()],
            },
        }
    }

    pub fn python_interpreter() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "code".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some(
                    "The Python 3 code to execute. Must use only the standard library. \
                     Use print() to emit results. Do not use file I/O or shell commands."
                        .to_string(),
                ),
                items: None,
            },
        );

        Tool {
            name: "python_interpreter".to_string(),
            description: "Executes a Python 3 snippet and returns its stdout output. \
                          Use this for complex calculations, statistical analysis, \
                          data transformation, or any logic the calculator cannot express."
                .to_string(),
            is_async: false,
            preopens: vec![],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["code".to_string()],
            },
        }
    }

    pub fn finalize_mission_state() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "summary".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some("A brief plain-text summary of all mission findings.".to_string()),
                items: None,
            },
        );
        properties.insert(
            "structured_data_payload".to_string(),
            ParameterProperty {
                prop_type: "object".to_string(),
                description: Some(
                    "MANDATORY JSON object containing all mission findings. \
                     Use descriptive keys (e.g. 'cheapest_flight', 'hotel_options', \
                     'total_cost'). Values may be strings, numbers, arrays, or nested \
                     objects. Focus on completeness and accuracy — the client renders \
                     this automatically."
                    .to_string(),
                ),
                items: None,
            },
        );
        properties.insert(
            "verification_logs".to_string(),
            ParameterProperty {
                prop_type: "array".to_string(),
                description: Some("Optional quality notes, data sources, or caveats.".to_string()),
                items: Some(Box::new(ParameterProperty {
                    prop_type: "string".to_string(),
                    description: None,
                    items: None,
                })),
            },
        );

        Tool {
            name: "finalize_mission_state".to_string(),
            description:
                "REQUIRED final-step tool. Submit all mission findings as a structured JSON \
                 state payload. Do not write plain text — call this tool exactly once with \
                 a complete structured_data_payload that captures every fact, number, \
                 comparison, and status the mission discovered."
                .to_string(),
            is_async: false,
            preopens: vec![],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["summary".to_string(), "structured_data_payload".to_string()],
            },
        }
    }

    pub fn feedback() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "question".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some(
                    "The question or decision you want the user to answer before work continues \
                     (e.g. 'The dashboard is ready — does the layout look correct?')."
                        .to_string(),
                ),
                items: None,
            },
        );
        properties.insert(
            "context".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some(
                    "Optional summary of what was accomplished so far, to give the user \
                     enough context to answer the question."
                        .to_string(),
                ),
                items: None,
            },
        );

        Tool {
            name: "feedback".to_string(),
            description:
                "Pause the mission and ask the human user a question. Use when you need \
                 approval, clarification, or a decision before continuing. The mission will \
                 resume once the user responds."
                    .to_string(),
            is_async: false,
            preopens: vec![],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["question".to_string()],
            },
        }
    }

    pub fn vision() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "file_path".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some(
                    "File name of the image in the uploads directory (e.g. 'chart.png'). \
                     Do not include directory separators or path prefixes."
                        .to_string(),
                ),
                items: None,
            },
        );
        properties.insert(
            "prompt".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some(
                    "Specific analysis question or instruction (e.g. \
                     'What data is shown in this chart?', 'Extract all visible text'). \
                     Defaults to a general description if omitted."
                        .to_string(),
                ),
                items: None,
            },
        );

        Tool {
            name: "vision".to_string(),
            description:
                "Analyze an image file and return a detailed textual description or data \
                 summary. Use for charts, photos, diagrams, and screenshots stored in the \
                 uploads/ directory."
                    .to_string(),
            is_async: true,
            preopens: vec![WasmPreopen {
                host: "uploads".to_string(),
                guest: "/uploads".to_string(),
                readonly: true,
            }],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["file_path".to_string()],
            },
        }
    }

    pub fn memory_persist() -> Self {
        let mut properties = HashMap::new();
        properties.insert(
            "key".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some(
                    "Unique identifier for this memory entry (alphanumeric, underscores, \
                     hyphens, max 64 chars). Example: 'user_industry', 'preferred_chart_style'"
                        .to_string(),
                ),
                items: None,
            },
        );
        properties.insert(
            "value".to_string(),
            ParameterProperty {
                prop_type: "string".to_string(),
                description: Some(
                    "The fact or context to remember. Be concise — max 2000 chars."
                        .to_string(),
                ),
                items: None,
            },
        );

        Tool {
            name: "memory_persist".to_string(),
            description:
                "Write a named fact to the persistent cross-mission memory store. \
                 Use this to save important findings, user preferences, or recurring context \
                 that should be available in future Axion missions."
                    .to_string(),
            is_async: false,
            preopens: vec![],
            parameters: ToolParameters {
                param_type: "object".to_string(),
                properties,
                required: vec!["key".to_string(), "value".to_string()],
            },
        }
    }

    /// Hydrate a `Tool` from a JSON manifest file on disk.
    ///
    /// The manifest must be valid JSON matching the `Tool` serde shape:
    /// `name`, `description`, `is_async` (bool), and `parameters` (JSON Schema).
    pub fn from_manifest(path: &std::path::Path) -> Result<Self, String> {
        let contents = std::fs::read_to_string(path)
            .map_err(|e| format!("Failed to read manifest {:?}: {}", path, e))?;
        serde_json::from_str::<Tool>(&contents)
            .map_err(|e| format!("Failed to parse manifest {:?}: {}", path, e))
    }
}

// ── Streaming events ──────────────────────────────────────────────────────────

/// Emitted through the mission channel as work progresses.
/// `serde(tag = "type")` puts the variant name into the JSON payload so the
/// frontend can switch on it without a separate SSE `event:` header lookup.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MissionUpdate {
    TaskStarted {
        slug: String,
        role: String,
        intent: String,
    },
    TaskCompleted {
        slug: String,
        role: String,
        result: String,
    },
    TaskFailed {
        slug: String,
        role: String,
    },
    GovernorExpand {
        new_task_count: usize,
        descriptions: Vec<String>,
    },
    MissionComplete {
        intent: String,
        task_count: usize,
        expanded_task_count: usize,
        mission_id: String,
        layout_hint: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        mission_state: Option<MissionState>,
    },
    MissionFailed {
        error: String,
    },
    /// The mission is paused and waiting for a human response before continuing.
    MissionPaused {
        /// The question the Governor wants the user to answer.
        question: String,
        /// Snapshot ID so the caller can persist/resume the mission.
        mission_id: String,
    },
}

impl MissionUpdate {
    /// Returns the SSE `event:` field value for this variant.
    pub fn event_name(&self) -> &'static str {
        match self {
            MissionUpdate::TaskStarted { .. }    => "task_started",
            MissionUpdate::TaskCompleted { .. }  => "task_completed",
            MissionUpdate::TaskFailed { .. }     => "task_failed",
            MissionUpdate::GovernorExpand { .. } => "governor_expand",
            MissionUpdate::MissionComplete { .. } => "mission_complete",
            MissionUpdate::MissionFailed { .. }  => "mission_failed",
            MissionUpdate::MissionPaused { .. }  => "mission_paused",
        }
    }
}
