"use client";

import { motion } from "framer-motion";

interface MissionStateSlim {
  data_payload: Record<string, unknown>;
  design_tokens?: { theme_preset?: string; layout_strategy?: string };
  suggested_widgets?: string[];
}

interface ActionBarProps {
  intent: string;
  missionState: MissionStateSlim;
  onNewMission: (intent: string) => void;
}

function extractSubject(intent: string): string {
  // Pull the most prominent noun-phrase from the intent string
  const stopwords = new Set(["a","an","the","and","or","for","in","on","of","to","into","about","with","from","by","is","are","was","were","do","does","did","how","what","why","when","where","who","which","that","this","these","those","will","can","could","should","would","let","make","create","build","plan","find","get","give","show","tell","write","design","analyze","research","synthesize","generate","develop","implement","compare","review","explain"]);
  const words = intent.replace(/['"]/g,"").split(/\s+/);
  const meaningful = words.filter(w => w.length > 2 && !stopwords.has(w.toLowerCase()));
  if (meaningful.length === 0) return intent.slice(0, 32);
  // Take up to 3 consecutive meaningful words
  return meaningful.slice(0, 3).join(" ");
}

function generateMarkdown(intent: string, data: Record<string, unknown>): string {
  const lines: string[] = [`# Mission Report: ${intent}`, "", `_Generated by Axion — ${new Date().toLocaleDateString()}_`, ""];
  for (const [key, value] of Object.entries(data)) {
    const title = key.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
    lines.push(`## ${title}`, "");
    if (Array.isArray(value)) {
      if (value.length > 0 && typeof value[0] === "object") {
        const headers = Object.keys(value[0] as object);
        lines.push(`| ${headers.join(" | ")} |`);
        lines.push(`| ${headers.map(()=>"---").join(" | ")} |`);
        for (const row of value) {
          const r = row as Record<string,unknown>;
          lines.push(`| ${headers.map(h=>String(r[h]??"")).join(" | ")} |`);
        }
      } else {
        for (const v of value) lines.push(`- ${v}`);
      }
    } else if (typeof value === "object" && value !== null) {
      for (const [k,v] of Object.entries(value as Record<string,unknown>)) {
        lines.push(`**${k.replace(/_/g," ")}**: ${v}`);
      }
    } else {
      lines.push(String(value));
    }
    lines.push("");
  }
  return lines.join("\n");
}

function downloadMarkdown(intent: string, data: Record<string, unknown>) {
  const md = generateMarkdown(intent, data);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `axion-report-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

const GLASS = {
  background: "rgba(255,255,255,0.05)",
  border: "1px solid rgba(255,255,255,0.11)",
  backdropFilter: "blur(40px)",
  WebkitBackdropFilter: "blur(40px)",
  boxShadow: "inset 0 1px 0 rgba(255,255,255,0.12), 0 4px 20px rgba(0,0,0,0.35)",
} as const;

export function ActionBar({ intent, missionState, onNewMission }: ActionBarProps) {
  const subject = extractSubject(intent);

  const strategy = missionState.design_tokens?.layout_strategy ?? "Overview";
  const thirdActionLabel =
    strategy === "FocusOnCharts" ? "Compare More Data" :
    strategy === "Narrative"     ? "Plan Next Steps" :
    strategy === "DataHeavy"     ? "Summarise Key Findings" :
                                   `Deep Dive: ${subject}`;
  const thirdActionIntent =
    strategy === "FocusOnCharts" ? `Compare alternative data sources for: ${subject}` :
    strategy === "Narrative"     ? `Create a detailed action plan based on: ${intent}` :
    strategy === "DataHeavy"     ? `Summarise and simplify the key findings from: ${intent}` :
                                   `Deep dive research into ${subject}`;

  const actions = [
    {
      icon: "↓",
      label: "Export Report",
      desc: "Download as Markdown",
      accent: "#6ee7b7",
      onClick: () => downloadMarkdown(intent, missionState.data_payload),
    },
    {
      icon: "⟳",
      label: "Refine Mission",
      desc: "Re-run with deeper focus",
      accent: "#8b9cf4",
      onClick: () => onNewMission(`Deeper analysis of: ${intent}`),
    },
    {
      icon: "→",
      label: thirdActionLabel,
      desc: "Spawn a follow-up mission",
      accent: "#f59e0b",
      onClick: () => onNewMission(thirdActionIntent),
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.25, duration: 0.35 }}
      style={{
        marginTop: 32,
        borderRadius: 20,
        overflow: "hidden",
        ...GLASS,
      }}
    >
      {/* Header */}
      <div style={{
        padding: "12px 20px",
        borderBottom: "1px solid rgba(255,255,255,0.07)",
        display: "flex",
        alignItems: "center",
        gap: 8,
      }}>
        <span style={{ fontSize: 9, fontWeight: 700, letterSpacing: "0.14em", textTransform: "uppercase", color: "rgba(255,255,255,0.28)" }}>
          Next Steps
        </span>
        <span style={{ flex: 1, height: 1, background: "rgba(255,255,255,0.06)" }} />
        <span style={{ width: 6, height: 6, borderRadius: "50%", background: "#34d399", boxShadow: "0 0 8px #34d399" }} />
        <span style={{ fontSize: 9, color: "rgba(52,211,153,0.7)", fontWeight: 500 }}>Mission complete</span>
      </div>

      {/* Actions */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 0 }}>
        {actions.map((a, i) => (
          <motion.button
            key={a.label}
            onClick={a.onClick}
            whileHover={{ background: `${a.accent}12` }}
            transition={{ duration: 0.15 }}
            style={{
              textAlign: "left",
              padding: "16px 20px",
              borderRight: i < 2 ? "1px solid rgba(255,255,255,0.07)" : "none",
              cursor: "pointer",
              background: "transparent",
              display: "flex",
              alignItems: "flex-start",
              gap: 12,
            }}
          >
            <span style={{
              width: 32, height: 32, borderRadius: 10, flexShrink: 0,
              display: "flex", alignItems: "center", justifyContent: "center",
              background: `${a.accent}18`,
              border: `1px solid ${a.accent}30`,
              color: a.accent,
              fontSize: 14, fontWeight: 700,
            }}>
              {a.icon}
            </span>
            <div>
              <p style={{ fontSize: 13, fontWeight: 600, color: "rgba(255,255,255,0.85)", marginBottom: 2 }}>
                {a.label}
              </p>
              <p style={{ fontSize: 11, color: "rgba(255,255,255,0.38)" }}>
                {a.desc}
              </p>
            </div>
          </motion.button>
        ))}
      </div>
    </motion.div>
  );
}
